### ISSUE TITLE
Complete scoreboard

### ISSUE THREAD

**Issue by Jesus0294** [moloch--/RootTheBox#130]
I'm not sure if this is an issue or I couldn't config to show completly the scoreboard.
After 3 days since start the game, the plataform only shows a 10 hours lapse of time on flags history.

Could you help me, if is possible, to config the plataform to show all the game history?

**Comment by jeffg2k** [comment]
Almost seems like it would be easier to just query and build the history on the fly like the summary page, but with timestamps and update via event trigger.  Sort of like notifications.  I'm not understanding the need to collect / send so much data .  Shouldn't we just need an entry for any time the data changes?  Why make a snapshot every 5 minutes when we can push a snapshot on an event?

I'm planning to run a game for months.  I can increase the snapshot interval, but do we need a snapshot interval?

**Comment by jeffg2k** [comment]
@moloch-- just wanted to ping you again on this.  The history is the last thing I'd like to address before sending the pull request for "v2.0" (or however you want to designate it if you accept the changes).  So far, all the changes in my fork have been additions / fixes / appearance.  I haven't changed anything in the core RTB function.  The history would be one I would consider changing the way it works.  Doing so would allow it to 1) be filtered based on date 2) allow you to delete teams 3) be faster with less redundant data.

I believe you're a better developer than I, so I'd like your input before I go modifying something that appears to be a good bit of work.  Here is what I'm currently thinking... what if we added a datetime column to the team_to_flag table.  When the history is called, it builds the data table doing a few things.  It grabs the data from team_to_flag based on the indexed datetime based on the requested time period (8hr, 1week, 1month, etc).  Create a team dictionary of score arrays. {"team1": [{"datetime": score}], "team2": [{"datetime": score}]}.  For each entry in the team_to_flag, create a before / after appending to the array.  This will give the graph a more immediate line step (could make this a 5 min diff if we want a short slope) as opposed to a gradual increase over the time period since last team capture.  Prepend a copy of 0 for the start timeframe and append a copy of length-1 for the endtime.  Session trigger on any team capture to update.

I think this would result in a data set that represents history, could be adjusted for a longer time period, would be much smaller in size than the current snapshot dataset, and wouldn't have an issue if you wanted to delete a team (could add a warning that it would delete all the team's game history).

Alternatively, maybe the current system could be reworked to make a snapshot before and after a capture update instead of a regular interval or would making an extremely large interval serve that purpose?

Thanks for any thoughts / advice / suggestions.  I'm also open to leaving it as is.. but I have concerns about how it would handle a game that lasts over extended periods.

**Comment by jeffg2k** [comment]
Hmm, just thought, the on the fly approach might have an issue capturing the history of dynamic scoring or penalties.

**Comment by jeffg2k** [comment]
So perhaps remove the callback based on interval and replace it with a take_snapshot before and after each event that changes the flags / score?  Wondering if that would cover everything...

**Comment by jeffg2k** [comment]
For now, I didn't change anything with the history backend.  To reduce data, the admin could just increase the snapshot timeframe.  To address the issue though, what I did was just create a data point selection, which maps to the length of the requesting websocket data.  So while not knowing the time frame, the user can at least request "more" data points in varying degrees.
https://github.com/jeffg2k/RootTheBox/commit/3c86599338f0f75db58082ae3f2370e5b4687d6e

**Comment by jeffg2k** [comment]
A "Data Points" drop down was added to allow users to select larger time frames for extended games.  Administrators may want to increase the history_snapshot_interval in the rootthebox.cfg for longer games to avoid large history sizes.
