### ISSUE TITLE
Can't re-register player due to MySQL duplicate entry

### ISSUE THREAD

**Issue by stealthsploit** [moloch--/RootTheBox#163]
After deleting a player, I can't re-register them (using the same handle) as MySQL errors on a duplicate entry, however when I check the DB there's no evidence of the player name anywhere. The error I receive is below after clicking 'Register Account'.

`IntegrityError: (_mysql_exceptions.IntegrityError) (1062, "Duplicate entry 'testuser' for key '_name'") [SQL: u'INSERT INTO team (created, uuid, _name, _motto, _avatar, code, money) VALUES (%s, %s, %s, %s, %s, %s, %s)'] [parameters: (datetime.datetime(2018, 9, 12, 20, 30, 24, 224488), '385305df-6dae-420d-a258-1a6a0a6c437d', 'testuser', '', None, 'ef33d6f8287447de', 0)] (Background on this error at: http://sqlalche.me/e/gkpj)`

Dropping and re-creating the db, follwed by importing my backup XML file seems to work ok, but would be nice not to have to do that each time.

**Comment by jeffg2k** [comment]
I've pushed a fix (https://github.com/moloch--/RootTheBox/commit/1b87c32c916770a2b6df19e537a0605e13b947bb) for this that will recreate the user account, but let me describe the issue.

The issue is that when the user account is deleted, we currently don't delete the associated team (as the team has snapshot dependencies).  When in player mode, it's essentially a team of one.  So it's not he user account you're getting an error on there, it's trying to create a new team with the same name (as the old team wasn't deleted with the user account).

I've changed it so that if the team name exists, it will use that team name.  It should still error out if another user exists with the same name, so this should only apply to your scenario.  However, since it's using the old team, things may not be properly "reset" if that team had flags captured and such.  That information still exists in the DB.  The best thing would be to delete the team along with the user account when in player mode, but that gets a bit more detailed (#64).  I do have some DB code that I'm testing that should allow us to delete teams, but not sure if it would cause any problems (@moloch--). It just sets some of the foreign keys to cascade, take no action, or null, which allows you to delete a team and all associated team snapshot data (requires memcache restart to reflect in History).

```
ALTER TABLE `rootthebox`.`snapshot_team` 
DROP FOREIGN KEY `snapshot_team_ibfk_1`;
ALTER TABLE `rootthebox`.`snapshot_team` 
ADD CONSTRAINT `snapshot_team_ibfk_1`
  FOREIGN KEY (`team_id`)
  REFERENCES `rootthebox`.`team` (`id`)
  ON DELETE CASCADE
  ON UPDATE RESTRICT;

ALTER TABLE `rootthebox`.`snapshot_team_to_game_level` 
DROP FOREIGN KEY `snapshot_team_to_game_level_ibfk_1`,
DROP FOREIGN KEY `snapshot_team_to_game_level_ibfk_2`;
ALTER TABLE `rootthebox`.`snapshot_team_to_game_level` 
ADD CONSTRAINT `snapshot_team_to_game_level_ibfk_1`
  FOREIGN KEY (`snapshot_team_id`)
  REFERENCES `rootthebox`.`snapshot_team` (`id`)
  ON DELETE CASCADE
  ON UPDATE RESTRICT,
ADD CONSTRAINT `snapshot_team_to_game_level_ibfk_2`
  FOREIGN KEY (`gam_level_id`)
  REFERENCES `rootthebox`.`game_level` (`id`)
  ON DELETE NO ACTION;

ALTER TABLE `rootthebox`.`snapshot_to_snapshot_team` 
DROP FOREIGN KEY `snapshot_to_snapshot_team_ibfk_2`;
ALTER TABLE `rootthebox`.`snapshot_to_snapshot_team` 
ADD CONSTRAINT `snapshot_to_snapshot_team_ibfk_2`
  FOREIGN KEY (`snapshot_team_id`)
  REFERENCES `rootthebox`.`snapshot_team` (`id`)
  ON DELETE CASCADE;

ALTER TABLE `rootthebox`.`team_to_game_level` 
DROP FOREIGN KEY `team_to_game_level_ibfk_2`;
ALTER TABLE `rootthebox`.`team_to_game_level` 
ADD CONSTRAINT `team_to_game_level_ibfk_2`
  FOREIGN KEY (`game_level_id`)
  REFERENCES `rootthebox`.`game_level` (`id`)
  ON DELETE NO ACTION;

ALTER TABLE `rootthebox`.`team_to_game_level` 
DROP FOREIGN KEY `team_to_game_level_ibfk_1`;
ALTER TABLE `rootthebox`.`team_to_game_level` 
ADD CONSTRAINT `team_to_game_level_ibfk_1`
  FOREIGN KEY (`team_id`)
  REFERENCES `rootthebox`.`team` (`id`)
  ON DELETE CASCADE
  ON UPDATE RESTRICT;

ALTER TABLE `rootthebox`.`user` 
DROP FOREIGN KEY `user_ibfk_1`;
ALTER TABLE `rootthebox`.`user` 
ADD CONSTRAINT `user_ibfk_1`
  FOREIGN KEY (`team_id`)
  REFERENCES `rootthebox`.`team` (`id`)
  ON DELETE SET NULL
  ON UPDATE RESTRICT;
```

**Comment by stealthsploit** [comment]
Thanks very much!

**Comment by jeffg2k** [comment]
Pushed another update for this which will reset the player's "team" values.  Only thing it doesn't get is the history.
