### ISSUE TITLE
Performances & Benchmark

### ISSUE THREAD

**Issue by garanews** [moloch--/RootTheBox#177]
Hello,
do you have some data regarding the HW vs n° users?
Do you have something to simulate n° users simultaneously in order to size correctly the environment?
Thanks

**Comment by moloch--** [comment]
Not really, the application isn't designed for massive scale but a modest machine should be able to handle a couple hundred users without too many problems. With a little work and a load balancer you could also deploy a multi-process environment to go a bit further.

**Comment by jeffg2k** [comment]
I was planning to see if I could get a game to run off a Raspberry Pi or an Intel NUC for easy classroom travel.  Would be a good test for minimal hardware.  

One measure you might be able to use is benchmarks or user measures for [Tornado Web Server](https://www.tornadoweb.org/).  RTB also utilizes memcached in production, so that gives a performance boost.
