### ISSUE TITLE
HTTPS

### ISSUE THREAD

**Issue by mohammadHmedat** [moloch--/RootTheBox#201]
Hello all;
I need a help in setting up the SSL certificate.
Could you provide me with the steps to set up the SSL for the rootthebox.

Thanks.

**Comment by jeffg2k** [comment]
It's been a little bit since i went through it, but I think the process is this:
1) Get cert - self-signed or issued ([Let's Encrypt](https://letsencrypt.org/) works great if it's public).
This should work for a self-signed:
`openssl req -x509 -newkey rsa:4096 -keyout key.pem -out cert.pem -days 365`
2) Edit your configuration file Server section - [See Wiki](https://github.com/moloch--/RootTheBox/wiki/Configuration-File-Details)

- SSL = True
- certfile = "path/to/cert.pem"
- keyfile = "path/to/key.pem"

I think that's it.

**Comment by jeffg2k** [comment]
I've added this to the [Wiki](https://github.com/moloch--/RootTheBox/wiki/Installation#ssltlshttps-optional)
