### ISSUE TITLE
Websocket Origin

### ISSUE THREAD

**Issue by jeffg2k** [moloch--/RootTheBox#245]
Documenting something that popped into my head but don't have the time to look at right now. 
 The default config for origin is "ws://localhost:8888", but I wonder if we should partly build this.

For example, if ssl = True, we should probably just set the protocol when we go to use origin to "wss" as the admin might not know that they should update the websocket config when setting up https (not understanding they operate a little differently).

Also, we already define port separately, so is there a reason to define it in origin as well?

Maybe the default config "origin" should just be "localhost" and then in our BaseHandlers initialize we set the protocol and port based on the other configuration options.

**Comment by moloch--** [comment]
I think the client side code does switch dynamically to `wss://` if the page was loaded over SSL, this value is specifically for validating the `origin` header in the websocket handshake to prevent [Cross-origin WebSocket Hijacking](https://www.christian-schneider.net/CrossSiteWebSocketHijacking.html) the `ws://` I think is actually ignored by the server and is only there to apease the `urlparse` library. 

The port number is included in this setting because if the app is configured with something like Nginx the app's listen port and the `origin` of the application will be different.
