### ISSUE TITLE
Filter by Field

### ISSUE THREAD

**Issue by mxamusic** [moloch--/RootTheBox#264]
Hey, I would like to add Field for teams, for example, University they are representing and later on I can filter based on University X or College Y in the statistics. 

Is that doable with current version :D since they CTF is for Universities I will get this request each uni wants a report of its student's score

**Comment by jeffg2k** [comment]
My latest thinking on #161 was to allow players / teams to associate themselves with a group.  So you could have something like /scoreboard?group=UofX and it would display the ranking of all players / teams in that group.  This could also be applied to statistics or other areas.  We could make it an array, so any player / team could be a member of multiple groups.  We could also have a configuration option for the scoreboard so that it's based on groups.  Thus you could have many schools all using the same ctf, but going to /scoreboard would only list their group, not all teams.

**Comment by mxamusic** [comment]
Also, since we are talking about grouping can we group the challenges by corporate so it looks like that 
Corporate A
-> Level 0
--> Challenge 1 
--> Challenge 2 
-> Level 1 
--> Challenge 1
--> Challenge 2 

Corporate B
-> Level 0
--> Challenge 1 , 2 ,3
-> Level 1

**Comment by jeffg2k** [comment]
I'm going to close this one as half was completed in v3.5 and other request is covered by completing #161
