### ISSUE TITLE
docker-compose does'nt work

### ISSUE THREAD

**Issue by thibaultserti** [moloch--/RootTheBox#280]
The docker-compose file is not working (I didn't change anything so)
It gives me a sqlite3 IntegityError 
[log.txt](https://github.com/moloch--/RootTheBox/files/3677342/log.txt)

**Comment by jeffg2k** [comment]
Thanks for the report.  The docker was initially done for testing Travis CI.  So it was only set up to run one time (thus setting up the db).  I've tried to update it so that it will only run the db setup on the first run when docker'd.  So you should be able to start / stop it without issue and it trying to recreate the database.  I also made it a bit clearer on the password and what ports it's running on as it was only reporting internal port mapping not the docker port map, which was on port 80.
