### ISSUE TITLE
 Too many levels to scroll

### ISSUE THREAD

**Issue by cohux** [moloch--/RootTheBox#314]
![image](https://user-images.githubusercontent.com/16814945/69926721-8d16a700-14f0-11ea-9485-7dfad101e349.png)

When there are too many question levels, the left column cannot scroll

**Comment by jeffg2k** [comment]
I can tell you where the problem is, but it will require some javascript skills to fix it (not sure I'm up to the task without a lot of experimentation).
The problem is the "affix" class (line 653) in `templates/admin/view/game_objects.html`.  This is intended to hold the left column in place as you scroll, however it does not position to the bottom when the column exceeds the page height.  One solution might be to remove the `affix` class, but this would make it more difficult to navigate when one doesn't have so many items.
The solution would be to have the position static (or unaffixed) until the last item can be seen and then fix it to the bottom.  If the bottom can be seen, then leave it as is (fixed to the top).

**Comment by jeffg2k** [comment]
After a bit of trial and error, I think I got something that works.  Just pushed a change if you can give that a try.

**Comment by cohux** [comment]
Solved, thanks
