### ISSUE TITLE
Question: External score servers ?

### ISSUE THREAD

**Issue by nunoguerreiro** [moloch--/RootTheBox#359]
Anyone has any idea how to integrate an external score server with RTB ?

**Comment by jeffg2k** [comment]
RTB supports [CTFTime](https://ctftime.org/).  You can access the feed via the Scoreboard menu when logged in as administrator. 
`/scoreboard/feed`
If there is another external score server you're thinking about?

**Comment by nunoguerreiro** [comment]
> RTB supports [CTFTime](https://ctftime.org/). You can access the feed via the Scoreboard menu when logged in as administrator.
> `/scoreboard/feed`
> Is there is another external score server you're thinking about?

none in particular yet... I'm trying some but could not find one that could be useful. 
Do you know any good one that can be used to monitor changes in services, ports, logins or even modifications inside a box ?

**Comment by jeffg2k** [comment]
Since the primary function of CTF software is the scoreboard mechanics, I think it might be hard to find something that separates that function.  I'm not aware of any that do, outside of supporting CTFTime, but you could look at picoCTF.  [picoCTF](https://github.com/picoCTF/picoCTF) is probably the most complex and advanced CTF from an architecture standpoint.  It has a steep learning curve but I'd think if anything could support an external scoreboard system, it would be picoCTF.
