### ISSUE TITLE
Language in Firefox 

### ISSUE THREAD

**Issue by BNYBLN030** [moloch--/RootTheBox#367]
the Language for Firefox with de_DE.csv doesnt work! In IE it works automatically ...
should I change something in the config?

**Comment by jeffg2k** [comment]
So, this is a bug in Tornado itself.  https://github.com/tornadoweb/tornado/issues/1858
I'll write a work around since it was reported in 2016 and they haven't fixed it.  Essentially the browser is returning `de` as an acceptable language and Tornado should choose the closet match, which is `de_DE`, but since it's not exact, it falls back to english.  This is in contrast to what their documentation says it should do.

**Comment by jeffg2k** [comment]
I've submitted a [pull request](https://github.com/tornadoweb/tornado/pull/2833) to Tornado with a fix.  I'm not sure if I should create a work around in RootTheBox (easy to do) or mark this pending a Tornado update.  @moloch-- thoughts?

I'd would add this code to BaseHandler in `get_user_locale()`:
```
codes = self.request.headers.get("Accept-Language")
if codes:
    for code in codes.split(","):
        code = code.split(";")[0]
        for l in locale.get_supported_locales():
            if code.lower() == l.split("_")[0]:
                return locale.get(l)
```

**Comment by jeffg2k** [comment]
Pushed up a temporary fix, since the Tornado folks have not commented on the issue or pull request.
