### ISSUE TITLE
SSL issue in subdomain

### ISSUE THREAD

**Issue by alahammad** [moloch--/RootTheBox#374]
Hello,

I have two issues one in ssl, i followed your instructions to add ssl but not working.
I got this error if http after configure ssl, and if ssl site gives me site not reachable, because not secure .

> Proxy Error
The proxy server received an invalid response from an upstream server.
The proxy server could not handle the request

Reason: Error reading from remote server
>

**Comment by jeffg2k** [comment]
If you're using a self signed cert, than you'll get a message that it's not secure as your browser can't validate the cert from a trusted authority.  It's still encrypted but you're browser doesn't trust a self-signed cert.  If you want a trusted cert, than you have to buy one for your domain or use something like [Let's Encrypt](https://letsencrypt.org/).  

As for the host unreachable, there could several issues since you're also trying to go through a proxy, which has its own potential configuration issues.  Make sure the SSL works first before setting up a proxy to it.   The connection string should be https and using the port that you've defined in the configuration (so it could be https://myserver:8888).  If you want, you can change it to the standard ssl port 443, but keep in mind that requires root or allowing python to bind to a lower port by using `sudo setcap CAP_NET_BIND_SERVICE=+eip /path/to/python`.  Once you're able to connect successfully, then you can move on to configure the proxy.

**Comment by jeffg2k** [comment]
Curious, you get it fixed? What was the issue?  Might help others searching for similar issue. :)
