### ISSUE TITLE
admin users - in scoreboard

### ISSUE THREAD

**Issue by nunoguerreiro** [moloch--/RootTheBox#384]
admin users are listed in scoreboard. Although they cannot play, does not make sense to have them in the scoreboard.

**Comment by jeffg2k** [comment]
That's not normally the case.  Not sure how that happened as an admin is not on a team and only teams are listed on the scoreboard.  If you have an admin in a team, remove them from it.

**Comment by nunoguerreiro** [comment]
ctf-admin user is administrator (role: Admin)

![image](https://user-images.githubusercontent.com/1771943/91671579-0c491200-eb39-11ea-8abb-b980a3e808a3.png)

then on scoreboard it appears also
![image](https://user-images.githubusercontent.com/1771943/91671590-2da9fe00-eb39-11ea-9c4b-ea5342422e9e.png)

and
![image](https://user-images.githubusercontent.com/1771943/91671594-3a2e5680-eb39-11ea-9191-d6c86f4d52ea.png)

**Comment by jeffg2k** [comment]
I think I figured out what was happening here.  If you use the User Management to change the a user from player to admin, it didn't remove them from the team (in the case of player mode - the team of 1).  Some listings, like the scoreboard and user management, filter out players with no team.  Since it didn't remove the team, the admin stayed listed on the scoreboard.  I've uploaded a fix that will remove them from the team when the admin role is set.  I've also set the user management to display admin accounts so that you can demote or delete them if needed, however I made it so you can't demote or delete yourself.

Note: your `ctf-admin` account will likely still be listed on the scoreboard until the team is removed from the account.  You can remove the team in the database directly, or after this update you can, with another admin account, demote the `ctf-admin` to a player account (save) and then promote it to an admin (save).  The latest RBT update should now remove the team as part of that process.
