### ISSUE TITLE
Default Theme not Working

### ISSUE THREAD

**Issue by AnthonyHerman** [moloch--/RootTheBox#396]
Hi there,

I'm trying to set the default theme for the server however it does not appear to be respected.

I'm importing an XML with the block:
```
<?xml version="1.0" ?>
<rootthebox api="1">
	<configuration>
		<default_theme>Bootstrap</default_theme>
	</configuration>
</rootthebox>
```
In the logs I'll see:
`webapp_1     | [I 200902 14:43:36 xmlsetup:275] Configuration (default_theme): Bootstrap`

And if I export my XML I'll see the block there. However the theme does not actually change and is stuck at Cyborg on both the home page and post-user registration.

Any ideas?

Thanks!

**Comment by jeffg2k** [comment]
Couple things.. when an account is created, including the admin account, the user theme value (stored in the database) is set based on the default theme at that time.  Thus updating the default theme will not change the theme of existing accounts, only new ones, unless you also include the configuration option `allow_user_to_change_theme=False` (the default is `True`).

Updating the default theme also required a restart of RTB to be visible pre-registration/login.  I plan to fix this so a restart will no longer be required.

**Comment by jeffg2k** [comment]
Did some more testing and I see what you're talking about.  The default theme is not set at user registration as I had thought.  It uses the database default value, which is `3` (`Cyborg`).  

I think it would be better if we didn't set a value here and just return the default_theme on Null, but it would require a database update as the field is set to Not Null and there is a foreign key constraint.  But doing that would allow an admin to update the theme and it would apply to all users who did not specifically set their theme to something else.  I expect this is probably a rare edge case though as most admins will set the theme before players register.  If the admin really wanted to update existing users, they could easily do so with SQL.

The simplest fix would be to just have the default_theme id used at account creation instead of `3`, like I thought it was doing.  For now, I think I'll just go with the simple fix unless we see demand for the other.
