### ISSUE TITLE
Unable to attached file in the box

### ISSUE THREAD

**Issue by PunitTailor55** [moloch--/RootTheBox#412]
Hi! I am creating cryptography task and I want to attached image for that particular task. Could you possibly tell me where should I supposed to add image for the task? I have tried while creating box but unable to add.

**Comment by packetgeek** [comment]
Suggestion: add it to a web server somewhere.  Provide the link in the Box description.  Instead of the usual "<a href='http:// " syntax,  use something along the lines of "inspect \[this image\]\(http://URL/image.png)" and it will show up as a link (i.e., use Markdown syntax for links).  If you want a blank line between the current one and the next, don't add a blank line (it won't show).  Instead, put two spaces at the end of the first line.  The interpreter will add the blank line.

**Comment by jeffg2k** [comment]
What @packetgeek suggested covers it pretty well, but here are a couple more tips.  Adding `inspect [this image](http://URL/image.png)` will create a link to the image.  Adding `inspect ![this image](http://URL/image.png)` will embed the image.  You'll need that exclamation point to render the image in the description.  As far as location, you could place the image in `/files/story` and then link to it like this `![crypto](/story/crypto.png)`.
