### ISSUE TITLE
DatabaseConnection:128] Cannot connect to database with any available driver

### ISSUE THREAD

**Issue by mr-1nc00r3ct** [moloch--/RootTheBox#420]
Hi, I have gone thru all the issues/solutions but couldn't find a fix for this. Whenever I try to ./rootthebox.py --setup=prod or even with docker, i'm getting the following error. I have tried to use the default db credentials but still no luck. the error 
is " DatabaseConnection:128] Cannot connect to database with any available driver. Verify correct username & password in rootthebox.cfg and db dependecies."

**Comment by jeffg2k** [comment]
I just did a build on the docker and didn't have any issues.  Make sure Python is 3.8.x or under (3.9 breaks things as they dropped backward compatibility for apps trying to support both Py2/3).  Maybe run `setup\depends.sh` if you're running mysql to make sure you have the needed drivers.

**Comment by mr-1nc00r3ct** [comment]
Can you try the same with manual installation and confirm? I need more customisation and control so I choosen manual installation. With docker it's up and running fine.

**Comment by jeffg2k** [comment]
What OS and version you running?  I'll try to spin up a VM.

**Comment by mr-1nc00r3ct** [comment]
Ubuntu 16.04

**Comment by jeffg2k** [comment]
Ubuntu 16.04 is a really difficult build to get working.  The install script doesn't work well and it's just a pain to get running.  I'd highly recommend 18.04 if you can install that.  It will make the python module issues disappear.  I just tested 18.04 and it worked good.  16.04 I got to the point where the database connected but it was a bit of a struggle (as mentioned above).  So a couple things to check.  

1.  Take a look at `/var/log/mysql/error.log`.  
1.  Make sure you can manually connect to the db using the username and password `mysql -u username -p`.  
1.  Make sure that the account has access to the database `grant all on rootthebox.* to '<user>'@'localhost';`.  
1.  Verify the `sql_password`, `sql_user` and `sql_database` are correct in the `rootthebox.cfg`.
1.  Add the `--debug` to command (`./rootthebox.py --setup=prod --debug`) 

Note on the debug, you may get a trace stack message of a missing module (something like `ModuleNotFoundError: No module named 'mysql'`).  That's likely because we try several different ways to connect.  So if it fails for one reason or another, it will try another way and you may not have the module for that other method.  In this example, you could install `pip3 install mysql-connector` to resolve that issue, but it likely won't fix the problem as it was just one attempt of many in case you had one set of drivers and not another.  The issue is likely one of the bullets listed above.

**Comment by mr-1nc00r3ct** [comment]
Hi, all the mentioned pointers are configures good but still I'm not able to make it work on Ubuntu 16.04. However, I have just tried the same on Ubuntu 18.04 and surprisingly it's working fine. Thanks
