### ISSUE TITLE
Captured Flag expand issue

### ISSUE THREAD

**Issue by nametovski** [moloch--/RootTheBox#460]
I enabled show_captured_flag but it seems that I am able to expand only some of the flags, I've tested in different boxes and from what I can see it is acting quite random, some can be expanded some not. Any quick fix?

**Comment by nametovski** [comment]
So the flag is captured by one team member and the other team members would like to list(expand) the description and eventually see the flag. This is working for some flags but for some is not expanding at all. This is the error from dev tools when I try to expand. 

Uncaught Error: Syntax error, unrecognized expression: unsupported pseudo: hover
It is referencing to:
static/js/pages/missions/box.js:43
static/js/pages/missions/box.js:42

**Comment by tetravaal4** [comment]
Tested the latest and it appears to be working! Thanks as always!

**Comment by jeffg2k** [comment]
@nametovski just a couple questions.  Did you change or update the included jQuery?  What browser & version are you using?

**Comment by nametovski** [comment]
Hey @jeffg2k , the issue occurs with the included jQuery, didn't had time to change it yet. I've tested with latest versions of Firefox, Chrome and Safari on Mac and Firefox on Windows. Same behavior on all of them.

**Comment by nametovski** [comment]
FYI, I exported the data from my production instance and imported it to my testing instance and I was able to expand the captured flags. Then I noticed that on my testing instance show_captured_flag was set to False so I changed it to True. After the service restart I was not able to expand the same flags also on my testing instance.

**Comment by jeffg2k** [comment]
Pushed an update for this.  Please let me know if it's still an issue.

**Comment by nametovski** [comment]
Unfortunately still the same issue. It is bit strange why on some of the flags works, I couldn't find any pattern so far.

**Comment by jeffg2k** [comment]
It's flags that have their own story.  What it's doing is checking to make sure you're not over (hover) the story button when you click to expand, otherwise you're trying to click the story button, not expand.   What line is it failing on now with the new code via the dev tools?  Want to make sure it actually updated the js from the cache.  If we have a new line, we can at least try and troubleshoot that.  The line that was causing the issue is `!$('.playstory').is(':hover')`.  I replaced that with a function to filter and then call `$(this).is(":hover")` as described here: https://gist.github.com/antydemant/74b00e27790e65f4555a29b73eea7bb2

But feel free to fiddle with with the `box.js` and see if you can find something that works.
