### ISSUE TITLE
Add mobile support

### ISSUE THREAD

**Issue by V0lk3n** [moloch--/RootTheBox#478]
Add support to addapt the page for a smartphone screen.

**Comment by eljeffeg** [comment]
This would be part of the feature request in #74 We just need to update bootstrap.  However, that's going to take a bit of work and it's been on the todo since 2015.  Mobile use is fairly limited in a CTF, since challenges usually require a computer. So the demand request hasn't been high.   We have a open "help requested" tag on that feature though if anyone wants to take up the challenge.  I'm going to close this issue as a duplicate.
