### ISSUE TITLE
login is successfull but re-directs back to login

### ISSUE THREAD

**Issue by bizzarecontacts** [moloch--/RootTheBox#499]
i have an issue where i try to login ( doesn't matter if its an admin or a registerd user ) it won't re-direct to the right page but instead returns to login page

what would be the issue? ( running on a windows machine not ubuntu )

**Comment by eljeffeg** [comment]
Likely the `origin` config setting, reverse proxy issue (if you're using one), or memcached.

**Comment by eljeffeg** [comment]
My first guess would be you're using nginx and didn't specify `x_headers = True` in the conifg.

**Comment by EtheriousNight** [comment]
Had the same prob. It was caused by a time difference between host and client. Dunno what the conditions are.

**Comment by bizzarecontacts** [comment]
alright, the fix was 

1. i had experienced it in 2 ocassions
a. on linux VM, it is incorrect or not matching times
b. in this case  ( to which I originally opened an issue ) , It was a windows OS, hence  the solution was : 

memcached needs to be manually downloaded and run prior to launching the framework.

now, some might be wondering why would you put that on an windows based os, the quick anwser is that in AWS that's more elegant. might want to add a FAQ or some form for others regarding these fixes.

**Comment by eljeffeg** [comment]
I'm not even sure 3.9 will work.  3.8 was the last version that I know worked.  3.9 removed a bunch of backward compatibility with 2.7.x.  RTB (and at least one dependency) still has code to support Python 2.7.x so that essentially broke it on 3.9.  We need to remove 2.7.x support to move forward, which we're fine with doing, just requires time and testing.

I'll try to find a place in the Wiki to insert that tip.
