### ISSUE TITLE
Accept Flag and email link issues

### ISSUE THREAD

**Issue by nametovski** [moloch--/RootTheBox#515]
Hello, 

When we accept answer and refund the penalty to the teams, it seems the database is not updated to reflect the player/team with the flags captured. In addition, the home page on the player is not updated, so I need to go and manually update the DB table with the flag/player IDs. Also, it would be nice to have the notification for the refund on the player side to list the flag/flag name which was refunded.

Additionally, if we set wss:// as the origin the link for email verification changes as well to wss://....... and with that, the players are not able to validate their email until they rename the wss to https. 

N.

**Comment by eljeffeg** [comment]
Thanks for the report - I've identified the email issue and will push up the change soon.  I'll look into the other issue tonight or tomorrow.

**Comment by eljeffeg** [comment]
Email fix in 3.11.1 and 3.12.0.  The accept answer update was added to 3.12.0.  The behavior in prior versions was tied into the penalty system (and restoring those points).  I decoupled it to allow the option to grant the flag and points when accepting the answer.  If penalties are enabled, it will restore that cost as well.

**Comment by nametovski** [comment]
I deployed the 3.12.0 and I can successfully accept the answer but the homepage of the player is still not updated. 
The first flag on the picture should be "green", If I go to missions and open the box, the flag is marked as captured via the player view.
<img width="480" alt="image" src="https://user-images.githubusercontent.com/15018959/195913809-4c39912d-0b5d-4518-94f0-394816abde63.png">

**Comment by eljeffeg** [comment]
You running in Player mode or Team mode?

**Comment by nametovski** [comment]
We use Teams, up to 4 players within Team. Any info about the player mode? Was that recently added?

**Comment by eljeffeg** [comment]
Player mode is just a Team of 1 with a few tweaks to the UI to make it look different.  Didn't seem to make sense to redesign the back end.  But I did add some things to allow the players to get some credit for team captures - reflected in the MVP.  And I guess I did add their own progress / skill tree on their user page regarding those credits.

I expect what you're seeing is the Team was granted the flag and the points, but the Player was not.  In Player mode, that wouldn't matter because the player statistics only exist in team mode.  In Player mode, the player is the Team so there are only Team statistics.. essentially, it wouldn't make sense to show two progress charts with the same data.  But in Team Mode, there are player statistics and that was not included in the challenge Accept code.  

I'll look to see if I can add that.  I'm not sure if statistics are created for a player's failed attempt - might just be a team fail.

**Comment by eljeffeg** [comment]
Pushed up a change.. the player id was not tracked for incorrect attempts.  I added this feature, but it will of course not be retroactive to prior challenge attempts.  Moving forward, it will grant the points / capture to the user and team.

**Comment by nametovski** [comment]
Can you check the wss issue on the link? I deployed the 3.12.0 and as user I am still getting wss link and not https.

**Comment by eljeffeg** [comment]
Do you have SSL set to False in the config? https://github.com/moloch--/RootTheBox/wiki/Configuration-File-Details#ssl

I can see where doing so would create an issue where you're saying SSL is False, but saying your Websocket is WSS.  In which case, I'm only trying to replace `ws://` with `http://` and thus `wss://` wouldn't replace anything.

But if we're SSL offloading, then SSL would correctly be False.  Trying to think how best to handle this...  Guess I'll replace `wss` with `https` even if SSL is False.

**Comment by eljeffeg** [comment]
Ok.. I think I got it this time.  In addition to the offloading issue, there was a second place where I needed to make the change.  Thanks for testing that.

**Comment by nametovski** [comment]
Let me know when you will push the changes so I can retest. When you are expecting to merge 3.12.0?

**Comment by eljeffeg** [comment]
Already pushed the fix to the 3.12.0 branch https://github.com/moloch--/RootTheBox/commit/2298e6e02074880163f7829b0c8ef97cedcded2e
As for the merge, I might look over the enhancement requests to see if there is anything quick I can add.  Otherwise, figured I'd give you, @PunitTailor55, @mxamusic, & @PJNorrisS1 a little time to test the fixes / features requested.  So maybe as early as Monday?  I can always push out an update if we find a new bug in it.

**Comment by PJNorrisS1** [comment]
Thank you for doing this. I have a few sessions next week so I will test Monday. I’m going to request a couple of enhancements soon, one is to have a “version” field for content (currently I store it in Org name) and include it in the new /status json. The other is to add more webhooks in, such as attempted flag (failed) and more info in the webhook. We want to compile stats on most popular flags etc and which ones are troublesome and when a hint is taken. 

Thank you!!
