### ISSUE TITLE
Saving data for incorrect forms

### ISSUE THREAD

**Issue by cgsilvers** [moloch--/RootTheBox#77]
Save the data in the input fields when there is an error creating a flag, box, user, etc.  If the user inputs something incorrectly all the information that they just entered disappears.

**Comment by jeffg2k** [comment]
I've tried to reduce the instances where the user can supply incorrect data via the form by specifying required fields and defining their type, min, max, pulling from existing data, etc.  If there is a specific form that's causing pain, it may make more sense to figure out what we can do to minimize failure rather than writing code that tries to maintain the form data and restore it upon invalid submissions.
